ALTER TABLE "ReferenceItem" ADD COLUMN "secondaryName" TEXT NOT NULL DEFAULT '';

UPDATE "ReferenceItem" SET "name" = 'บังคลาเทศ', "secondaryName" = 'BANGLADESH' WHERE "type" = 'province' AND "code" = 'BANGLADESH' AND "nationCode" = 'BD';
UPDATE "ReferenceItem" SET "name" = 'จีนในฝรั่งเศษ', "secondaryName" = 'CHINA-FR' WHERE "type" = 'province' AND "code" = 'CHINA-FR' AND "nationCode" = 'CFR';
UPDATE "ReferenceItem" SET "name" = 'อานฮุย/เหอเฟย์', "secondaryName" = 'ANHUI' WHERE "type" = 'province' AND "code" = 'ANHUI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ปักกิ่ง (เป่ยจิง)', "secondaryName" = 'BEIJING' WHERE "type" = 'province' AND "code" = 'BEIJING' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'จีน', "secondaryName" = 'CHINA' WHERE "type" = 'province' AND "code" = 'CHINA' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ฉงฉิ่ง', "secondaryName" = 'CHONGQING' WHERE "type" = 'province' AND "code" = 'CHONGQING' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ CCT', "secondaryName" = 'CTCCT' WHERE "type" = 'province' AND "code" = 'CTCCT' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์หลงไท่', "secondaryName" = 'CTCLV' WHERE "type" = 'province' AND "code" = 'CTCLV' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์โกลบอล', "secondaryName" = 'CTGB' WHERE "type" = 'province' AND "code" = 'CTGB' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์LIAN TAI ( LLT )', "secondaryName" = 'CTLLT' WHERE "type" = 'province' AND "code" = 'CTLLT' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ LLTC', "secondaryName" = 'CTLLTC' WHERE "type" = 'province' AND "code" = 'CTLLTC' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์เหลียนไท่ (LT)', "secondaryName" = 'CTLT' WHERE "type" = 'province' AND "code" = 'CTLT' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์เหลียนไท่ ( 2 )', "secondaryName" = 'CTLT-2' WHERE "type" = 'province' AND "code" = 'CTLT-2' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์เหลียนไท่ (HONGTHAI)', "secondaryName" = 'CTLTH' WHERE "type" = 'province' AND "code" = 'CTLTH' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ LTP(THAI HONG DA)', "secondaryName" = 'CTLTP' WHERE "type" = 'province' AND "code" = 'CTLTP' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์LIAN TAI ( LTS )', "secondaryName" = 'CTLTS' WHERE "type" = 'province' AND "code" = 'CTLTS' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์หลงไท่', "secondaryName" = 'CTLV' WHERE "type" = 'province' AND "code" = 'CTLV' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์หลงเถิง', "secondaryName" = 'CTLX' WHERE "type" = 'province' AND "code" = 'CTLX' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์หลงเถิง WY', "secondaryName" = 'CTLXWY' WHERE "type" = 'province' AND "code" = 'CTLXWY' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาร์เตอร์เหม่ยจิงเทียนเซี้ย', "secondaryName" = 'CTMJTX' WHERE "type" = 'province' AND "code" = 'CTMJTX' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์โอเวอร์ซีร์', "secondaryName" = 'CTOCT' WHERE "type" = 'province' AND "code" = 'CTOCT' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ พิมดี', "secondaryName" = 'CTPD' WHERE "type" = 'province' AND "code" = 'CTPD' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ตงฟางฮอลิเดย์', "secondaryName" = 'CTTFH' WHERE "type" = 'province' AND "code" = 'CTTFH' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ จิวหยุ่น TJY', "secondaryName" = 'CTTJY' WHERE "type" = 'province' AND "code" = 'CTTJY' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ ทีเคแอล', "secondaryName" = 'CTTKL' WHERE "type" = 'province' AND "code" = 'CTTKL' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ทีเคแอล1', "secondaryName" = 'CTTKL-1' WHERE "type" = 'province' AND "code" = 'CTTKL-1' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ทีเอ็นจี', "secondaryName" = 'CTTNG' WHERE "type" = 'province' AND "code" = 'CTTNG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ไทยเทียนซุ่น', "secondaryName" = 'CTTTX' WHERE "type" = 'province' AND "code" = 'CTTTX' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ ไทซิงว่าง', "secondaryName" = 'CTTXW' WHERE "type" = 'province' AND "code" = 'CTTXW' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ ซินต๋า', "secondaryName" = 'CTXD' WHERE "type" = 'province' AND "code" = 'CTXD' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ยูเหม่ย', "secondaryName" = 'CTYM' WHERE "type" = 'province' AND "code" = 'CTYM' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ฝู๋เจี้ยน (ฮกเกี้ยน)/ฝูโจว', "secondaryName" = 'FUJIAN' WHERE "type" = 'province' AND "code" = 'FUJIAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'การซู (หลานโจว)', "secondaryName" = 'GANSU' WHERE "type" = 'province' AND "code" = 'GANSU' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'กวางตุ้ง/กวางโจว/ซ่านโถว/เซินเจิ้น/จงซาน', "secondaryName" = 'GUANGDONG' WHERE "type" = 'province' AND "code" = 'GUANGDONG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'กว่างซี/หนานหนิง/กุ้ยหลิน', "secondaryName" = 'GUANGXI' WHERE "type" = 'province' AND "code" = 'GUANGXI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'กุ้ยโจว (กุ้ยหยาง)', "secondaryName" = 'GUIZHOU' WHERE "type" = 'province' AND "code" = 'GUIZHOU' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ไห่หนาน (ไหหลำ)/ไหโข่ว', "secondaryName" = 'HAINAN' WHERE "type" = 'province' AND "code" = 'HAINAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เหอเป่ย (ฉือเจียจวง)', "secondaryName" = 'HEBEI' WHERE "type" = 'province' AND "code" = 'HEBEI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เฮยหลงเจียง/ฮาร์บิน', "secondaryName" = 'HEILONGJIANG' WHERE "type" = 'province' AND "code" = 'HEILONGJIANG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เหอหนาน/เจิ้งโจว', "secondaryName" = 'HENAN' WHERE "type" = 'province' AND "code" = 'HENAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'หูเป่ย/อู่ฮั่น', "secondaryName" = 'HUBEI' WHERE "type" = 'province' AND "code" = 'HUBEI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'หูหนาน (ฉางชา)', "secondaryName" = 'HUNAN' WHERE "type" = 'province' AND "code" = 'HUNAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เจียงซู/หนานจิง(นานกิง)/ซูโจว', "secondaryName" = 'JIANGSU' WHERE "type" = 'province' AND "code" = 'JIANGSU' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เจียงซี/หนานฉาง', "secondaryName" = 'JIANGXI' WHERE "type" = 'province' AND "code" = 'JIANGXI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'จี้หลิง/ฉางชุน', "secondaryName" = 'JILIN' WHERE "type" = 'province' AND "code" = 'JILIN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เหลียวหนิง/เสิ่นหยาง/ต้าเหลียน', "secondaryName" = 'LIAONING' WHERE "type" = 'province' AND "code" = 'LIAONING' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชาเตอร์ LLTS', "secondaryName" = 'LLTS' WHERE "type" = 'province' AND "code" = 'LLTS' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'มองโกเลีย', "secondaryName" = 'MONGOLIA' WHERE "type" = 'province' AND "code" = 'MGL' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เน่ย์เหมิงกู่', "secondaryName" = 'NEIMENGGU' WHERE "type" = 'province' AND "code" = 'NEIMENGGU' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'หนิงเซี้ย', "secondaryName" = 'NINGXIA' WHERE "type" = 'province' AND "code" = 'NINGXIA' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'จีนอื่นๆ', "secondaryName" = 'OTHER CHINA' WHERE "type" = 'province' AND "code" = 'OTHER CHINA' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ชิงไห่ (ซีหนิง)', "secondaryName" = 'QINGHAI' WHERE "type" = 'province' AND "code" = 'QINGHAI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ส่านซี (ซีอาน)', "secondaryName" = 'SHAANXI' WHERE "type" = 'province' AND "code" = 'SHAANXI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ซานตง /จีหนาน /เยี่ยนไถ', "secondaryName" = 'SHANDONG' WHERE "type" = 'province' AND "code" = 'SHANDONG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เซียงไฮ้', "secondaryName" = 'SHANGHAI' WHERE "type" = 'province' AND "code" = 'SHANGHAI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ซานซี (ไท่หยวน)', "secondaryName" = 'SHANXI' WHERE "type" = 'province' AND "code" = 'SHANXI' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ซื่อชวน(เสฉวน)/เฉิงตู (เฉินตู)', "secondaryName" = 'SICHUAN' WHERE "type" = 'province' AND "code" = 'SICHUAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เทียนจิง', "secondaryName" = 'TIANJIN' WHERE "type" = 'province' AND "code" = 'TIANJIN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'อู่ฮัน', "secondaryName" = 'WU HAN' WHERE "type" = 'province' AND "code" = 'WU HAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ซินเจียง', "secondaryName" = 'XINJIANG' WHERE "type" = 'province' AND "code" = 'XINJIANG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'ซีจ้าง', "secondaryName" = 'XIZHANG' WHERE "type" = 'province' AND "code" = 'XIZHANG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'หยุนหนาน(ยูนนาน)/คุนหมิง', "secondaryName" = 'YUNNAN' WHERE "type" = 'province' AND "code" = 'YUNNAN' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'จางโจว', "secondaryName" = 'ZHANG ZHOU' WHERE "type" = 'province' AND "code" = 'ZHANG ZHOU' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'เจ้อเจียง (หังโจว) / หนิงโป', "secondaryName" = 'ZHEJIANG' WHERE "type" = 'province' AND "code" = 'ZHEJIANG' AND "nationCode" = 'CN';
UPDATE "ReferenceItem" SET "name" = 'จีนในนิวซีแลนด์', "secondaryName" = 'CH-New Zeland' WHERE "type" = 'province' AND "code" = 'CH-NEW ZELAND' AND "nationCode" = 'CNL';
UPDATE "ReferenceItem" SET "name" = 'จีนในอเมริกา', "secondaryName" = 'CHINA IN USA' WHERE "type" = 'province' AND "code" = 'CHINA IN USA' AND "nationCode" = 'CUS';
UPDATE "ReferenceItem" SET "name" = 'จีนในเวียดนาม', "secondaryName" = 'CHINA IN VIETNAM' WHERE "type" = 'province' AND "code" = 'CHINA IN VIETNAM' AND "nationCode" = 'CVN';
UPDATE "ReferenceItem" SET "name" = 'ยุโรป', "secondaryName" = 'EUROPE' WHERE "type" = 'province' AND "code" = 'EUROPE' AND "nationCode" = 'EU';
UPDATE "ReferenceItem" SET "name" = 'ยุโรปรวม', "secondaryName" = 'OTHER EUROPE' WHERE "type" = 'province' AND "code" = 'OTHER EUROPE' AND "nationCode" = 'EU';
UPDATE "ReferenceItem" SET "name" = 'อเมริกา', "secondaryName" = 'อเมริกา' WHERE "type" = 'province' AND "code" = 'USA' AND "nationCode" = 'EU';
UPDATE "ReferenceItem" SET "name" = 'ประเทศฝรั่งเศส', "secondaryName" = 'FRANCE' WHERE "type" = 'province' AND "code" = 'FRANCE' AND "nationCode" = 'FR';
UPDATE "ReferenceItem" SET "name" = 'ฝรั่งเศสในอเมริกา', "secondaryName" = 'FRANCE-USA' WHERE "type" = 'province' AND "code" = 'FRANCE-USA' AND "nationCode" = 'FUS';
UPDATE "ReferenceItem" SET "name" = 'อังการี', "secondaryName" = 'HUNGARY' WHERE "type" = 'province' AND "code" = 'HUNGARY' AND "nationCode" = 'HG';
UPDATE "ReferenceItem" SET "name" = 'ฮ่องกง', "secondaryName" = 'HONGKONG' WHERE "type" = 'province' AND "code" = 'HONGKONG' AND "nationCode" = 'HK';
UPDATE "ReferenceItem" SET "name" = 'อินโดนีเซีย', "secondaryName" = 'INDONESIA' WHERE "type" = 'province' AND "code" = 'INDONESIA' AND "nationCode" = 'ID';
UPDATE "ReferenceItem" SET "name" = 'อินเดีย', "secondaryName" = 'INDIA' WHERE "type" = 'province' AND "code" = 'INDIA' AND "nationCode" = 'IND';
UPDATE "ReferenceItem" SET "name" = 'อิหร่าน', "secondaryName" = 'IRAN' WHERE "type" = 'province' AND "code" = 'IRAN' AND "nationCode" = 'IR';
UPDATE "ReferenceItem" SET "name" = 'ญี่ปุ่น', "secondaryName" = 'JAPAN' WHERE "type" = 'province' AND "code" = 'JAPAN' AND "nationCode" = 'JP';
UPDATE "ReferenceItem" SET "name" = 'เกาหลี', "secondaryName" = 'KOREA' WHERE "type" = 'province' AND "code" = 'KOREA' AND "nationCode" = 'KR';
UPDATE "ReferenceItem" SET "name" = 'ลาว', "secondaryName" = 'LAOS' WHERE "type" = 'province' AND "code" = 'LAOS' AND "nationCode" = 'LA';
UPDATE "ReferenceItem" SET "name" = 'โมร็อกโก', "secondaryName" = 'MOROCCO' WHERE "type" = 'province' AND "code" = 'MOROCCO' AND "nationCode" = 'MC';
UPDATE "ReferenceItem" SET "name" = 'พม่า', "secondaryName" = 'MYANMAR' WHERE "type" = 'province' AND "code" = 'MYANMAR' AND "nationCode" = 'MM';
UPDATE "ReferenceItem" SET "name" = 'มองโกเลีย', "secondaryName" = 'MONGOLIA' WHERE "type" = 'province' AND "code" = 'MN' AND "nationCode" = 'MN';
UPDATE "ReferenceItem" SET "name" = 'มาเลเซีย', "secondaryName" = 'MALAYSIA' WHERE "type" = 'province' AND "code" = 'MALAYSIA' AND "nationCode" = 'MY';
UPDATE "ReferenceItem" SET "name" = 'ไม่รู้มณฑล', "secondaryName" = 'ไม่รู้มณฑล' WHERE "type" = 'province' AND "code" = 'ไม่รู้มณฑล' AND "nationCode" = 'NO';
UPDATE "ReferenceItem" SET "name" = 'พิลิปปินส์', "secondaryName" = 'PHILIPPINES' WHERE "type" = 'province' AND "code" = 'PHILIPPINES' AND "nationCode" = 'PH';
UPDATE "ReferenceItem" SET "name" = 'พิลิปนส์ในเอเมริกา', "secondaryName" = 'PH-USA' WHERE "type" = 'province' AND "code" = 'PH-USA' AND "nationCode" = 'PUS';
UPDATE "ReferenceItem" SET "name" = 'PRIVATE', "secondaryName" = 'PRIVATE' WHERE "type" = 'province' AND "code" = 'PRIVATE' AND "nationCode" = 'PV';
UPDATE "ReferenceItem" SET "name" = 'รัสเซีย', "secondaryName" = 'RUSSIA' WHERE "type" = 'province' AND "code" = 'RUSSIA' AND "nationCode" = 'RU';
UPDATE "ReferenceItem" SET "name" = 'SYRIAN ARAB REPUBL', "secondaryName" = 'SYRIAN ARAB REPUBL' WHERE "type" = 'province' AND "code" = 'SYRIAN ARAB REPUBL' AND "nationCode" = 'SY';
UPDATE "ReferenceItem" SET "name" = 'TAXI', "secondaryName" = 'TAXI' WHERE "type" = 'province' AND "code" = 'TAXI' AND "nationCode" = 'TAXI';
UPDATE "ReferenceItem" SET "name" = 'TOURIST PLUS CARD', "secondaryName" = 'TOURIST PLUS CARD' WHERE "type" = 'province' AND "code" = 'TOURIST PLUS CARD' AND "nationCode" = 'TPC';
UPDATE "ReferenceItem" SET "name" = 'ตุรกี', "secondaryName" = 'TURKY' WHERE "type" = 'province' AND "code" = 'TURKY' AND "nationCode" = 'TR';
UPDATE "ReferenceItem" SET "name" = 'ไตหวัน', "secondaryName" = 'TAIWAN' WHERE "type" = 'province' AND "code" = 'TAIWAN' AND "nationCode" = 'TW';
UPDATE "ReferenceItem" SET "name" = 'ไต้หวันอื่นๆ', "secondaryName" = 'OTHER TAIWAN' WHERE "type" = 'province' AND "code" = 'TO' AND "nationCode" = 'TW';
UPDATE "ReferenceItem" SET "name" = 'จีนในอเมริกา', "secondaryName" = 'CHINA-US' WHERE "type" = 'province' AND "code" = 'CHINA-US' AND "nationCode" = 'US';
UPDATE "ReferenceItem" SET "name" = 'จีนในยุโรป คุณวิเชียร', "secondaryName" = 'CHINA-US1' WHERE "type" = 'province' AND "code" = 'CHINA-US1' AND "nationCode" = 'US1';
UPDATE "ReferenceItem" SET "name" = 'จีนในยุโรป Ms. Yang', "secondaryName" = 'CHINA-US2' WHERE "type" = 'province' AND "code" = 'CHINA-US2' AND "nationCode" = 'US2';
UPDATE "ReferenceItem" SET "name" = 'เวียดนามในออสเตรเลีย', "secondaryName" = 'VN-AUS' WHERE "type" = 'province' AND "code" = 'VN-AUS' AND "nationCode" = 'VAS';
UPDATE "ReferenceItem" SET "name" = 'เวียดนาม', "secondaryName" = 'VIETNAM' WHERE "type" = 'province' AND "code" = 'VIETNAM' AND "nationCode" = 'VN';
UPDATE "ReferenceItem" SET "name" = 'เวียดนามในอเมริกา', "secondaryName" = 'V-IN-USA' WHERE "type" = 'province' AND "code" = 'V-IN-USA' AND "nationCode" = 'VUS';
UPDATE "ReferenceItem" SET "name" = 'WAIT', "secondaryName" = 'WAIT' WHERE "type" = 'province' AND "code" = 'WAIT' AND "nationCode" = 'WAIT';
UPDATE "ReferenceItem" SET "name" = 'WALK IN', "secondaryName" = 'WALK IN' WHERE "type" = 'province' AND "code" = 'WALK IN' AND "nationCode" = 'WI';
