CREATE TABLE "ReferenceItem" (
  "id" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "nationCode" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "ReferenceItem_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ReferenceItem_type_code_nationCode_key" ON "ReferenceItem"("type", "code", "nationCode");
CREATE INDEX "ReferenceItem_type_idx" ON "ReferenceItem"("type");
CREATE INDEX "ReferenceItem_type_nationCode_idx" ON "ReferenceItem"("type", "nationCode");

INSERT INTO "ReferenceItem" ("id", "type", "code", "name", "nationCode", "updatedAt") VALUES
  ('ref-nation', 'nation', '-', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-ad', 'nation', 'AD', 'ANDORRA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ae', 'nation', 'AE', 'UNITED ARAB EMIRATES (UAE.)', '', CURRENT_TIMESTAMP),
  ('ref-nation-aeu', 'nation', 'AEU', 'Asia In Europe & America', '', CURRENT_TIMESTAMP),
  ('ref-nation-af', 'nation', 'AF', 'AFGHANISTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-ag', 'nation', 'AG', 'ANTIGUA AND BARBUDA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ai', 'nation', 'AI', 'ANGUILLA', '', CURRENT_TIMESTAMP),
  ('ref-nation-al', 'nation', 'AL', 'ALBANIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-all', 'nation', 'ALL', 'ALL NATION', '', CURRENT_TIMESTAMP),
  ('ref-nation-am', 'nation', 'AM', 'AMENIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ao', 'nation', 'AO', 'ANGOLA', '', CURRENT_TIMESTAMP),
  ('ref-nation-aq', 'nation', 'AQ', 'ANTARCTICA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ar', 'nation', 'AR', 'ARGENTINA', '', CURRENT_TIMESTAMP),
  ('ref-nation-as', 'nation', 'AS', 'AMERICAN SAMOA', '', CURRENT_TIMESTAMP),
  ('ref-nation-at', 'nation', 'AT', 'AUSTRIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-au', 'nation', 'AU', 'AUSTRALIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-aus', 'nation', 'AUS', 'CHINESE IN AUSTRALIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-aw', 'nation', 'AW', 'ARUBA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ax', 'nation', 'AX', 'ALAND ISLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-az', 'nation', 'AZ', 'AZERBAIJAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-ba', 'nation', 'BA', 'BOSNIA AND HERZEGOVINA', '', CURRENT_TIMESTAMP),
  ('ref-nation-bb', 'nation', 'BB', 'BARBADOS', '', CURRENT_TIMESTAMP),
  ('ref-nation-bd', 'nation', 'BD', 'BANGLADESH', '', CURRENT_TIMESTAMP),
  ('ref-nation-be', 'nation', 'BE', 'BELGIUM', '', CURRENT_TIMESTAMP),
  ('ref-nation-bf', 'nation', 'BF', 'BURKINA FASO', '', CURRENT_TIMESTAMP),
  ('ref-nation-bg', 'nation', 'BG', 'BULGARIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-bh', 'nation', 'BH', 'BAHRAIN', '', CURRENT_TIMESTAMP),
  ('ref-nation-bi', 'nation', 'BI', 'BURUNDI', '', CURRENT_TIMESTAMP),
  ('ref-nation-bj', 'nation', 'BJ', 'BENIN', '', CURRENT_TIMESTAMP),
  ('ref-nation-bl', 'nation', 'BL', 'SAINT BARTHELEMY', '', CURRENT_TIMESTAMP),
  ('ref-nation-bm', 'nation', 'BM', 'BERMUDA', '', CURRENT_TIMESTAMP),
  ('ref-nation-bn', 'nation', 'BN', 'BRUNIE DARUSSALAM', '', CURRENT_TIMESTAMP),
  ('ref-nation-bo', 'nation', 'BO', 'BOLIVIA,PLURINATIONAL', '', CURRENT_TIMESTAMP),
  ('ref-nation-bq', 'nation', 'BQ', 'BONAIRE,SINT EUSTATIUS AND SABA', '', CURRENT_TIMESTAMP),
  ('ref-nation-br', 'nation', 'BR', 'BRAZIL', '', CURRENT_TIMESTAMP),
  ('ref-nation-bs', 'nation', 'BS', 'BAHAMAS', '', CURRENT_TIMESTAMP),
  ('ref-nation-bt', 'nation', 'BT', 'BHUTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-bv', 'nation', 'BV', 'BOUVET ISLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-bw', 'nation', 'BW', 'BOTSWANA', '', CURRENT_TIMESTAMP),
  ('ref-nation-by', 'nation', 'BY', 'BELARUS', '', CURRENT_TIMESTAMP),
  ('ref-nation-bz', 'nation', 'BZ', 'BELIZE', '', CURRENT_TIMESTAMP),
  ('ref-nation-c', 'nation', 'C', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-c0288', 'nation', 'C0288', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-c0341', 'nation', 'C0341', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-ca', 'nation', 'CA', 'CANADA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cc', 'nation', 'CC', 'COCOS (KEELING) ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-cd', 'nation', 'CD', 'CONGO,THE DEMOCRATIC REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-cd10', 'nation', 'CD10', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-cf', 'nation', 'CF', 'CENTRAL AFRICAN REPLUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-cfr', 'nation', 'CFR', 'CHINA-FR', '', CURRENT_TIMESTAMP),
  ('ref-nation-cg', 'nation', 'CG', 'CONGO', '', CURRENT_TIMESTAMP),
  ('ref-nation-ch', 'nation', 'CH', 'SWITZERLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-ci', 'nation', 'CI', 'COTE D''IVOIRE', '', CURRENT_TIMESTAMP),
  ('ref-nation-ck', 'nation', 'CK', 'COOK ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-cl', 'nation', 'CL', 'CHILE', '', CURRENT_TIMESTAMP),
  ('ref-nation-cm', 'nation', 'CM', 'CAMEROON', '', CURRENT_TIMESTAMP),
  ('ref-nation-cn', 'nation', 'CN', 'CHINA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cnz', 'nation', 'CNZ', 'Chinese In New Zealand', '', CURRENT_TIMESTAMP),
  ('ref-nation-co', 'nation', 'CO', 'COLOMBIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cr', 'nation', 'CR', 'COSTA RICA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cu', 'nation', 'CU', 'CUBA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cus', 'nation', 'CUS', 'CHINA IN USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-cv', 'nation', 'CV', 'CAPE VERDE', '', CURRENT_TIMESTAMP),
  ('ref-nation-cvn', 'nation', 'CVN', 'CHINA IN VIETNAM', '', CURRENT_TIMESTAMP),
  ('ref-nation-cw', 'nation', 'CW', 'CURACAO', '', CURRENT_TIMESTAMP),
  ('ref-nation-cx', 'nation', 'CX', 'CHRISTMAS ISLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-cy', 'nation', 'CY', 'CYPRUS', '', CURRENT_TIMESTAMP),
  ('ref-nation-cz', 'nation', 'CZ', 'CZECH REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-db', 'nation', 'DB', 'DUBAI', '', CURRENT_TIMESTAMP),
  ('ref-nation-de', 'nation', 'DE', 'GERMANY', '', CURRENT_TIMESTAMP),
  ('ref-nation-dj', 'nation', 'DJ', 'DJIBOUTI', '', CURRENT_TIMESTAMP),
  ('ref-nation-dk', 'nation', 'DK', 'DENMARK', '', CURRENT_TIMESTAMP),
  ('ref-nation-dm', 'nation', 'DM', 'DOMINICA', '', CURRENT_TIMESTAMP),
  ('ref-nation-do', 'nation', 'DO', 'DOMINICAN REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-dz', 'nation', 'DZ', 'ALGERIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ec', 'nation', 'EC', 'ECUADOR', '', CURRENT_TIMESTAMP),
  ('ref-nation-eg', 'nation', 'EG', 'EGYPT', '', CURRENT_TIMESTAMP),
  ('ref-nation-eh', 'nation', 'EH', 'WESTERN SAHARA', '', CURRENT_TIMESTAMP),
  ('ref-nation-eree', 'nation', 'EREE', 'ERITREAESTONIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-es', 'nation', 'ES', 'SPAIN', '', CURRENT_TIMESTAMP),
  ('ref-nation-et', 'nation', 'ET', 'ETHIOPIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-eu', 'nation', 'EU', 'EUROPE', '', CURRENT_TIMESTAMP),
  ('ref-nation-fa', 'nation', 'FA', 'FALKLAND ISLANDS(MALVINAS)', '', CURRENT_TIMESTAMP),
  ('ref-nation-fi', 'nation', 'FI', 'FINLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-fj', 'nation', 'FJ', 'FIJI', '', CURRENT_TIMESTAMP),
  ('ref-nation-fm', 'nation', 'FM', 'MICRONESIA''FEDERATED STATES OF', '', CURRENT_TIMESTAMP),
  ('ref-nation-fo', 'nation', 'FO', 'FAROE ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-fr', 'nation', 'FR', 'FRANCE', '', CURRENT_TIMESTAMP),
  ('ref-nation-fus', 'nation', 'FUS', 'FRANCE-USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ga', 'nation', 'GA', 'GABON', '', CURRENT_TIMESTAMP),
  ('ref-nation-gb', 'nation', 'GB', 'UNITED KINGDOM (ENGLAND)', '', CURRENT_TIMESTAMP),
  ('ref-nation-gd', 'nation', 'GD', 'GUANGDONG,    (GRENADA)', '', CURRENT_TIMESTAMP),
  ('ref-nation-ge', 'nation', 'GE', 'GEORGIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gf', 'nation', 'GF', 'FRENCH GUIANA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gg', 'nation', 'GG', 'GUERNSEY', '', CURRENT_TIMESTAMP),
  ('ref-nation-gh', 'nation', 'GH', 'GHANA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gi', 'nation', 'GI', 'GIBRALTAR', '', CURRENT_TIMESTAMP),
  ('ref-nation-gl', 'nation', 'GL', 'GREEN LAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-gm', 'nation', 'GM', 'BAMBIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gn', 'nation', 'GN', 'GUINEA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gow', 'nation', 'GOW', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-gp', 'nation', 'GP', 'GUADELOUPE', '', CURRENT_TIMESTAMP),
  ('ref-nation-gq', 'nation', 'GQ', 'EQUATORIAL GUINEA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gr', 'nation', 'GR', 'GREECE', '', CURRENT_TIMESTAMP),
  ('ref-nation-grs', 'nation', 'GRS', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-gs', 'nation', 'GS', 'SOUTH GEORGIA & SOUTH SANDWICH ISLA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gst', 'nation', 'GST', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-gt', 'nation', 'GT', 'GUATEMALA', '', CURRENT_TIMESTAMP),
  ('ref-nation-gu', 'nation', 'GU', 'GUAM', '', CURRENT_TIMESTAMP),
  ('ref-nation-gw', 'nation', 'GW', 'GUINEA-BISSAU', '', CURRENT_TIMESTAMP),
  ('ref-nation-gy', 'nation', 'GY', 'GUYANA', '', CURRENT_TIMESTAMP),
  ('ref-nation-hg', 'nation', 'HG', 'HUNGARY', '', CURRENT_TIMESTAMP),
  ('ref-nation-hk', 'nation', 'HK', 'HONG KONG', '', CURRENT_TIMESTAMP),
  ('ref-nation-hm', 'nation', 'HM', 'HEARD ISLAND AND MCDONALD ISLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-hn', 'nation', 'HN', 'HONDURAS', '', CURRENT_TIMESTAMP),
  ('ref-nation-hr', 'nation', 'HR', 'CROATIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ht', 'nation', 'HT', 'AHITI', '', CURRENT_TIMESTAMP),
  ('ref-nation-id', 'nation', 'ID', 'INDONESIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ie', 'nation', 'IE', 'IRELAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-il', 'nation', 'IL', 'ISRAEL', '', CURRENT_TIMESTAMP),
  ('ref-nation-im', 'nation', 'IM', 'ISLE OF MAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-ind', 'nation', 'IND', 'INDIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-io', 'nation', 'IO', 'BRITISH INDIAN OCEAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-iq', 'nation', 'IQ', 'IRAQ', '', CURRENT_TIMESTAMP),
  ('ref-nation-ir', 'nation', 'IR', 'IRAN,ISLAMIC REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-is', 'nation', 'IS', 'ICELAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-it', 'nation', 'IT', 'ITALY', '', CURRENT_TIMESTAMP),
  ('ref-nation-je', 'nation', 'JE', 'JERSEY', '', CURRENT_TIMESTAMP),
  ('ref-nation-jet', 'nation', 'JET', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-jm', 'nation', 'JM', 'JAMAICA', '', CURRENT_TIMESTAMP),
  ('ref-nation-jo', 'nation', 'JO', 'JORDAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-jp', 'nation', 'JP', 'JAPAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-ke', 'nation', 'KE', 'KENYA', '', CURRENT_TIMESTAMP),
  ('ref-nation-kg', 'nation', 'KG', 'KYRGYZSTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-kh', 'nation', 'KH', 'CAMBODIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ki', 'nation', 'KI', 'KIRIBATI', '', CURRENT_TIMESTAMP),
  ('ref-nation-km', 'nation', 'KM', 'COMOROS', '', CURRENT_TIMESTAMP),
  ('ref-nation-kn', 'nation', 'KN', 'SAINT KITTS AND NEVIS', '', CURRENT_TIMESTAMP),
  ('ref-nation-kor', 'nation', 'KOR', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-kp', 'nation', 'KP', 'KOREA,DEMOCRATIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-kr', 'nation', 'KR', 'KOREA REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-kw', 'nation', 'KW', 'KUWAIT', '', CURRENT_TIMESTAMP),
  ('ref-nation-ky', 'nation', 'KY', 'CAYMAN ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-kz', 'nation', 'KZ', 'KAZAKHSTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-la', 'nation', 'LA', 'LAO PEOPLE''S DEMOCRATIC REBUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-lb', 'nation', 'LB', 'LEBANON', '', CURRENT_TIMESTAMP),
  ('ref-nation-lc', 'nation', 'LC', 'SAINT LUCIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-li', 'nation', 'LI', 'LIECHTENSTEIN', '', CURRENT_TIMESTAMP),
  ('ref-nation-lk', 'nation', 'LK', 'SRI LANKA', '', CURRENT_TIMESTAMP),
  ('ref-nation-lr', 'nation', 'LR', 'LIBERIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ls', 'nation', 'LS', 'LESOTHO', '', CURRENT_TIMESTAMP),
  ('ref-nation-lt', 'nation', 'LT', 'LITHUANIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-lu', 'nation', 'LU', 'LUXEMBOURG', '', CURRENT_TIMESTAMP),
  ('ref-nation-lv', 'nation', 'LV', 'LATVIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-lxrpk', 'nation', 'LXRPK', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-ly', 'nation', 'LY', 'LIBYAN ARAB JAMAHIRIYA', '', CURRENT_TIMESTAMP),
  ('ref-nation-mc', 'nation', 'MC', 'MOROCCO', '', CURRENT_TIMESTAMP),
  ('ref-nation-md', 'nation', 'MD', 'MOLDOVA''REPUBLIC OF', '', CURRENT_TIMESTAMP),
  ('ref-nation-me', 'nation', 'ME', 'MONTIENEGRO', '', CURRENT_TIMESTAMP),
  ('ref-nation-meg', 'nation', 'MEG', 'Middle East Asai', '', CURRENT_TIMESTAMP),
  ('ref-nation-mf', 'nation', 'MF', 'SAINT MARTIN (FRENCH PART)', '', CURRENT_TIMESTAMP),
  ('ref-nation-mg', 'nation', 'MG', 'MADAGASCAR', '', CURRENT_TIMESTAMP),
  ('ref-nation-mh', 'nation', 'MH', 'MARSHALL ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-mk', 'nation', 'MK', 'MACEDONIA''THE FORMER YUGOSLAV RE.', '', CURRENT_TIMESTAMP),
  ('ref-nation-ml', 'nation', 'ML', 'MALI', '', CURRENT_TIMESTAMP),
  ('ref-nation-mm', 'nation', 'MM', 'MYANMAR', '', CURRENT_TIMESTAMP),
  ('ref-nation-mn', 'nation', 'MN', 'MONGOLIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-mo', 'nation', 'MO', 'MACAO', '', CURRENT_TIMESTAMP),
  ('ref-nation-mp', 'nation', 'MP', 'NORTHERN MARIANA ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-mq', 'nation', 'MQ', 'MARTINIQUE', '', CURRENT_TIMESTAMP),
  ('ref-nation-mr', 'nation', 'MR', 'MAURITANIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ms', 'nation', 'MS', 'MONTSERRAT', '', CURRENT_TIMESTAMP),
  ('ref-nation-mt', 'nation', 'MT', 'MALTA', '', CURRENT_TIMESTAMP),
  ('ref-nation-mu', 'nation', 'MU', 'MAURITIUS', '', CURRENT_TIMESTAMP),
  ('ref-nation-mv', 'nation', 'MV', 'VALDIVES', '', CURRENT_TIMESTAMP),
  ('ref-nation-mw', 'nation', 'MW', 'MALAWI', '', CURRENT_TIMESTAMP),
  ('ref-nation-mx', 'nation', 'MX', 'MEXICO', '', CURRENT_TIMESTAMP),
  ('ref-nation-my', 'nation', 'MY', 'MALAYSIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-mz', 'nation', 'MZ', 'MOZAMBIQUE', '', CURRENT_TIMESTAMP),
  ('ref-nation-na', 'nation', 'NA', 'NAMIBIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-nc', 'nation', 'NC', 'NEW CALEDONIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ne', 'nation', 'NE', 'NIGER', '', CURRENT_TIMESTAMP),
  ('ref-nation-nf', 'nation', 'NF', 'NORFOLK ISLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-ng', 'nation', 'NG', 'NIGERIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ni', 'nation', 'NI', 'NICARAGUA', '', CURRENT_TIMESTAMP),
  ('ref-nation-nl', 'nation', 'NL', 'NETHERLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-no', 'nation', 'NO', 'No Nation', '', CURRENT_TIMESTAMP),
  ('ref-nation-none', 'nation', 'NONE', 'No Nation', '', CURRENT_TIMESTAMP),
  ('ref-nation-np', 'nation', 'NP', 'NEPAL', '', CURRENT_TIMESTAMP),
  ('ref-nation-nr', 'nation', 'NR', 'NAURU', '', CURRENT_TIMESTAMP),
  ('ref-nation-nu', 'nation', 'NU', 'NIUE', '', CURRENT_TIMESTAMP),
  ('ref-nation-nz', 'nation', 'NZ', 'NEW ZEALAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-om', 'nation', 'OM', 'OMAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-orc', 'nation', 'ORC', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-pa', 'nation', 'PA', 'PANAMA', '', CURRENT_TIMESTAMP),
  ('ref-nation-pe', 'nation', 'PE', 'PERU', '', CURRENT_TIMESTAMP),
  ('ref-nation-pf', 'nation', 'PF', 'FRENCH POLYNESIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-pg', 'nation', 'PG', 'PAPUA NEW GUINEA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ph', 'nation', 'PH', 'PHILIPPINES', '', CURRENT_TIMESTAMP),
  ('ref-nation-pk', 'nation', 'PK', 'PAKISTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-pl', 'nation', 'PL', 'POLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-pm', 'nation', 'PM', 'SAINT PIERRE AND MIQUELON', '', CURRENT_TIMESTAMP),
  ('ref-nation-pn', 'nation', 'PN', 'PITCAIRN', '', CURRENT_TIMESTAMP),
  ('ref-nation-pr', 'nation', 'PR', 'PUERTO RICO', '', CURRENT_TIMESTAMP),
  ('ref-nation-ps', 'nation', 'PS', 'PALESTINIAN TERRITORY''OCCUPIED', '', CURRENT_TIMESTAMP),
  ('ref-nation-pt', 'nation', 'PT', 'PORTUGAL', '', CURRENT_TIMESTAMP),
  ('ref-nation-pus', 'nation', 'PUS', 'PH-USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-pv', 'nation', 'PV', 'PRIVATE', '', CURRENT_TIMESTAMP),
  ('ref-nation-pw', 'nation', 'PW', 'PALAU', '', CURRENT_TIMESTAMP),
  ('ref-nation-py', 'nation', 'PY', 'PARAGUAY', '', CURRENT_TIMESTAMP),
  ('ref-nation-qa', 'nation', 'QA', 'QATAR', '', CURRENT_TIMESTAMP),
  ('ref-nation-re', 'nation', 'RE', 'REUNION', '', CURRENT_TIMESTAMP),
  ('ref-nation-ro', 'nation', 'RO', 'ROMANIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-ru', 'nation', 'RU', 'RUSSIAN FEDERATION', '', CURRENT_TIMESTAMP),
  ('ref-nation-rw', 'nation', 'RW', 'RWANDA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sa', 'nation', 'SA', 'SAUDI ARABIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sb', 'nation', 'SB', 'SERBIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sc', 'nation', 'SC', 'SICHUAN      (SEYCHELLES)', '', CURRENT_TIMESTAMP),
  ('ref-nation-sd', 'nation', 'SD', 'SUDAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-se', 'nation', 'SE', 'SWEDEN', '', CURRENT_TIMESTAMP),
  ('ref-nation-sg', 'nation', 'SG', 'SINGAPORE', '', CURRENT_TIMESTAMP),
  ('ref-nation-sh', 'nation', 'SH', 'SAINT HELENA ASCENSION', '', CURRENT_TIMESTAMP),
  ('ref-nation-si', 'nation', 'SI', 'SLOVENIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sj', 'nation', 'SJ', 'SVALBARD AND JAN MAYEN SWAZILAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-sk', 'nation', 'SK', 'SLOVAKIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sl', 'nation', 'SL', 'SIERRA LEONE', '', CURRENT_TIMESTAMP),
  ('ref-nation-sm', 'nation', 'SM', 'SAN MARINO', '', CURRENT_TIMESTAMP),
  ('ref-nation-sn', 'nation', 'SN', 'SENEGAL', '', CURRENT_TIMESTAMP),
  ('ref-nation-so', 'nation', 'SO', 'SOMALIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-sr', 'nation', 'SR', 'SURINAME', '', CURRENT_TIMESTAMP),
  ('ref-nation-ss', 'nation', 'SS', 'SOUTH SUDAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-st', 'nation', 'ST', 'SAO TOME AND PRINCIPE', '', CURRENT_TIMESTAMP),
  ('ref-nation-stl', 'nation', 'STL', '-', '', CURRENT_TIMESTAMP),
  ('ref-nation-sv', 'nation', 'SV', 'EL SALVADOR', '', CURRENT_TIMESTAMP),
  ('ref-nation-sx', 'nation', 'SX', 'SINT MAARTEN (DUTCH PART)', '', CURRENT_TIMESTAMP),
  ('ref-nation-sy', 'nation', 'SY', 'SYRIAN ARAB REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-sz', 'nation', 'SZ', 'SCOTLAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-ta', 'nation', 'TA', 'TAXI CHINA / KOREA', '', CURRENT_TIMESTAMP),
  ('ref-nation-taxi', 'nation', 'TAXI', 'TAXI', '', CURRENT_TIMESTAMP),
  ('ref-nation-tc', 'nation', 'TC', 'TURKS AND CAICOS ISLANDS', '', CURRENT_TIMESTAMP),
  ('ref-nation-td', 'nation', 'TD', 'CHAD', '', CURRENT_TIMESTAMP),
  ('ref-nation-tf', 'nation', 'TF', 'FRENCH SOUTHERN', '', CURRENT_TIMESTAMP),
  ('ref-nation-tg', 'nation', 'TG', 'TOGO', '', CURRENT_TIMESTAMP),
  ('ref-nation-th', 'nation', 'TH', 'THAILAND', '', CURRENT_TIMESTAMP),
  ('ref-nation-tj', 'nation', 'TJ', 'TAJIKISTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-tk', 'nation', 'TK', 'TOKELAU', '', CURRENT_TIMESTAMP),
  ('ref-nation-tl', 'nation', 'TL', 'TIMOR-LESTE', '', CURRENT_TIMESTAMP),
  ('ref-nation-tm', 'nation', 'TM', 'TURKMENISTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-tn', 'nation', 'TN', 'TUNISIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-to', 'nation', 'TO', 'TONGA', '', CURRENT_TIMESTAMP),
  ('ref-nation-tpc', 'nation', 'TPC', 'TOURIST PLUS CARD', '', CURRENT_TIMESTAMP),
  ('ref-nation-tr', 'nation', 'TR', 'TURKEY', '', CURRENT_TIMESTAMP),
  ('ref-nation-tt', 'nation', 'TT', 'TRINIDAD AND TOBAGO', '', CURRENT_TIMESTAMP),
  ('ref-nation-tus', 'nation', 'TUS', 'T-IN-USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-tv', 'nation', 'TV', 'TUVALU', '', CURRENT_TIMESTAMP),
  ('ref-nation-tw', 'nation', 'TW', 'TAIWAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-tz', 'nation', 'TZ', 'TANZANIA''UNITED REPUBLIC', '', CURRENT_TIMESTAMP),
  ('ref-nation-ua', 'nation', 'UA', 'UKRAINE', '', CURRENT_TIMESTAMP),
  ('ref-nation-ug', 'nation', 'UG', 'UGANDA', '', CURRENT_TIMESTAMP),
  ('ref-nation-um', 'nation', 'UM', 'UNITED STATES MINOR', '', CURRENT_TIMESTAMP),
  ('ref-nation-us', 'nation', 'US', 'USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-us1', 'nation', 'US1', 'CHINA-US1', '', CURRENT_TIMESTAMP),
  ('ref-nation-us2', 'nation', 'US2', 'CHINA-US2', '', CURRENT_TIMESTAMP),
  ('ref-nation-uy', 'nation', 'UY', 'URUGUAY', '', CURRENT_TIMESTAMP),
  ('ref-nation-uz', 'nation', 'UZ', 'UZBEKISTAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-va', 'nation', 'VA', 'HOLY SEE (VATICAN CITY STATE)', '', CURRENT_TIMESTAMP),
  ('ref-nation-vas', 'nation', 'VAS', 'VN-AUS', '', CURRENT_TIMESTAMP),
  ('ref-nation-vc', 'nation', 'VC', 'SAINT VINCENT AND GRENADINES', '', CURRENT_TIMESTAMP),
  ('ref-nation-ve', 'nation', 'VE', 'VENEZUELA''BOLIVARIAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-vg', 'nation', 'VG', 'VIRGIN ISLAND''BRITISH', '', CURRENT_TIMESTAMP),
  ('ref-nation-vi', 'nation', 'VI', 'VIRGIN ISLANDS''US.', '', CURRENT_TIMESTAMP),
  ('ref-nation-vn', 'nation', 'VN', 'VIET NAM', '', CURRENT_TIMESTAMP),
  ('ref-nation-vu', 'nation', 'VU', 'VANUATU', '', CURRENT_TIMESTAMP),
  ('ref-nation-vus', 'nation', 'VUS', 'V-IN-USA', '', CURRENT_TIMESTAMP),
  ('ref-nation-wait', 'nation', 'WAIT', 'WAIT', '', CURRENT_TIMESTAMP),
  ('ref-nation-wf', 'nation', 'WF', 'WALLIS AND FUTUNA', '', CURRENT_TIMESTAMP),
  ('ref-nation-wi', 'nation', 'WI', 'WALK IN', '', CURRENT_TIMESTAMP),
  ('ref-nation-ww', 'nation', 'WW', 'WORLD WIDE', '', CURRENT_TIMESTAMP),
  ('ref-nation-ye', 'nation', 'YE', 'YEMAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-yn', 'nation', 'YN', 'YUNNAN', '', CURRENT_TIMESTAMP),
  ('ref-nation-yt', 'nation', 'YT', 'MAYOTTE', '', CURRENT_TIMESTAMP),
  ('ref-nation-za', 'nation', 'ZA', 'SOUTH AFRICA', '', CURRENT_TIMESTAMP),
  ('ref-nation-zm', 'nation', 'ZM', 'ZAMBIA', '', CURRENT_TIMESTAMP),
  ('ref-nation-zw', 'nation', 'ZW', 'ZIMBABWE', '', CURRENT_TIMESTAMP),
  ('ref-nation-zx', 'nation', 'ZX', 'No Nation', '', CURRENT_TIMESTAMP),
  ('ref-province-bd-bangladesh', 'province', 'BANGLADESH', 'BANGLADESH', 'BD', CURRENT_TIMESTAMP),
  ('ref-province-cfr-china-fr', 'province', 'CHINA-FR', 'CHINA-FR', 'CFR', CURRENT_TIMESTAMP),
  ('ref-province-cn-anhui', 'province', 'ANHUI', 'ANHUI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-beijing', 'province', 'BEIJING', 'BEIJING', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-china', 'province', 'CHINA', 'CHINA', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-chongqing', 'province', 'CHONGQING', 'CHONGQING', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctcct', 'province', 'CTCCT', 'CTCCT', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctclv', 'province', 'CTCLV', 'CTCLV', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctgb', 'province', 'CTGB', 'CTGB', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctllt', 'province', 'CTLLT', 'CTLLT', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlltc', 'province', 'CTLLTC', 'CTLLTC', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlt', 'province', 'CTLT', 'CTLT', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlt-2', 'province', 'CTLT-2', 'CTLT-2', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlth', 'province', 'CTLTH', 'CTLTH', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctltp', 'province', 'CTLTP', 'CTLTP', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlts', 'province', 'CTLTS', 'CTLTS', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlv', 'province', 'CTLV', 'CTLV', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlx', 'province', 'CTLX', 'CTLX', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctlxwy', 'province', 'CTLXWY', 'CTLXWY', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctmjtx', 'province', 'CTMJTX', 'CTMJTX', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctoct', 'province', 'CTOCT', 'CTOCT', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctpd', 'province', 'CTPD', 'CTPD', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttfh', 'province', 'CTTFH', 'CTTFH', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttjy', 'province', 'CTTJY', 'CTTJY', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttkl', 'province', 'CTTKL', 'CTTKL', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttkl-1', 'province', 'CTTKL-1', 'CTTKL-1', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttng', 'province', 'CTTNG', 'CTTNG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctttx', 'province', 'CTTTX', 'CTTTX', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-cttxw', 'province', 'CTTXW', 'CTTXW', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctxd', 'province', 'CTXD', 'CTXD', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ctym', 'province', 'CTYM', 'CTYM', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-fujian', 'province', 'FUJIAN', 'FUJIAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-gansu', 'province', 'GANSU', 'GANSU', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-guangdong', 'province', 'GUANGDONG', 'GUANGDONG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-guangxi', 'province', 'GUANGXI', 'GUANGXI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-guizhou', 'province', 'GUIZHOU', 'GUIZHOU', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-hainan', 'province', 'HAINAN', 'HAINAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-hebei', 'province', 'HEBEI', 'HEBEI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-heilongjiang', 'province', 'HEILONGJIANG', 'HEILONGJIANG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-henan', 'province', 'HENAN', 'HENAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-hubei', 'province', 'HUBEI', 'HUBEI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-hunan', 'province', 'HUNAN', 'HUNAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-jiangsu', 'province', 'JIANGSU', 'JIANGSU', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-jiangxi', 'province', 'JIANGXI', 'JIANGXI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-jilin', 'province', 'JILIN', 'JILIN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-liaoning', 'province', 'LIAONING', 'LIAONING', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-llts', 'province', 'LLTS', 'LLTS', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-mgl', 'province', 'MGL', 'MONGOLIA', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-neimenggu', 'province', 'NEIMENGGU', 'NEIMENGGU', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-ningxia', 'province', 'NINGXIA', 'NINGXIA', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-other-china', 'province', 'OTHER CHINA', 'OTHER CHINA', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-qinghai', 'province', 'QINGHAI', 'QINGHAI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-shaanxi', 'province', 'SHAANXI', 'SHAANXI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-shandong', 'province', 'SHANDONG', 'SHANDONG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-shanghai', 'province', 'SHANGHAI', 'SHANGHAI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-shanxi', 'province', 'SHANXI', 'SHANXI', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-sichuan', 'province', 'SICHUAN', 'SICHUAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-tianjin', 'province', 'TIANJIN', 'TIANJIN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-wu-han', 'province', 'WU HAN', 'WU HAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-xinjiang', 'province', 'XINJIANG', 'XINJIANG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-xizhang', 'province', 'XIZHANG', 'XIZHANG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-yunnan', 'province', 'YUNNAN', 'YUNNAN', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-zhang-zhou', 'province', 'ZHANG ZHOU', 'ZHANG ZHOU', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cn-zhejiang', 'province', 'ZHEJIANG', 'ZHEJIANG', 'CN', CURRENT_TIMESTAMP),
  ('ref-province-cnl-ch-new-zeland', 'province', 'CH-NEW ZELAND', 'CH-New Zeland', 'CNL', CURRENT_TIMESTAMP),
  ('ref-province-cus-china-in-usa', 'province', 'CHINA IN USA', 'CHINA IN USA', 'CUS', CURRENT_TIMESTAMP),
  ('ref-province-cvn-china-in-vietnam', 'province', 'CHINA IN VIETNAM', 'CHINA IN VIETNAM', 'CVN', CURRENT_TIMESTAMP),
  ('ref-province-eu-europe', 'province', 'EUROPE', 'EUROPE', 'EU', CURRENT_TIMESTAMP),
  ('ref-province-eu-other-europe', 'province', 'OTHER EUROPE', 'OTHER EUROPE', 'EU', CURRENT_TIMESTAMP),
  ('ref-province-eu-usa', 'province', 'USA', 'อเมริกา', 'EU', CURRENT_TIMESTAMP),
  ('ref-province-fr-france', 'province', 'FRANCE', 'FRANCE', 'FR', CURRENT_TIMESTAMP),
  ('ref-province-fus-france-usa', 'province', 'FRANCE-USA', 'FRANCE-USA', 'FUS', CURRENT_TIMESTAMP),
  ('ref-province-hg-hungary', 'province', 'HUNGARY', 'HUNGARY', 'HG', CURRENT_TIMESTAMP),
  ('ref-province-hk-hongkong', 'province', 'HONGKONG', 'HONGKONG', 'HK', CURRENT_TIMESTAMP),
  ('ref-province-id-indonesia', 'province', 'INDONESIA', 'INDONESIA', 'ID', CURRENT_TIMESTAMP),
  ('ref-province-ind-india', 'province', 'INDIA', 'INDIA', 'IND', CURRENT_TIMESTAMP),
  ('ref-province-ir-iran', 'province', 'IRAN', 'IRAN', 'IR', CURRENT_TIMESTAMP),
  ('ref-province-jp-japan', 'province', 'JAPAN', 'JAPAN', 'JP', CURRENT_TIMESTAMP),
  ('ref-province-kr-korea', 'province', 'KOREA', 'KOREA', 'KR', CURRENT_TIMESTAMP),
  ('ref-province-la-laos', 'province', 'LAOS', 'LAOS', 'LA', CURRENT_TIMESTAMP),
  ('ref-province-mc-morocco', 'province', 'MOROCCO', 'MOROCCO', 'MC', CURRENT_TIMESTAMP),
  ('ref-province-mm-myanmar', 'province', 'MYANMAR', 'MYANMAR', 'MM', CURRENT_TIMESTAMP),
  ('ref-province-mn-mn', 'province', 'MN', 'MONGOLIA', 'MN', CURRENT_TIMESTAMP),
  ('ref-province-my-malaysia', 'province', 'MALAYSIA', 'MALAYSIA', 'MY', CURRENT_TIMESTAMP),
  ('ref-province-no', 'province', 'ไม่รู้มณฑล', 'ไม่รู้มณฑล', 'NO', CURRENT_TIMESTAMP),
  ('ref-province-ph-philippines', 'province', 'PHILIPPINES', 'PHILIPPINES', 'PH', CURRENT_TIMESTAMP),
  ('ref-province-pus-ph-usa', 'province', 'PH-USA', 'PH-USA', 'PUS', CURRENT_TIMESTAMP),
  ('ref-province-pv-private', 'province', 'PRIVATE', 'PRIVATE', 'PV', CURRENT_TIMESTAMP),
  ('ref-province-ru-russia', 'province', 'RUSSIA', 'RUSSIA', 'RU', CURRENT_TIMESTAMP),
  ('ref-province-sy-syrian-arab-republ', 'province', 'SYRIAN ARAB REPUBL', 'SYRIAN ARAB REPUBL', 'SY', CURRENT_TIMESTAMP),
  ('ref-province-taxi-taxi', 'province', 'TAXI', 'TAXI', 'TAXI', CURRENT_TIMESTAMP),
  ('ref-province-tpc-tourist-plus-card', 'province', 'TOURIST PLUS CARD', 'TOURIST PLUS CARD', 'TPC', CURRENT_TIMESTAMP),
  ('ref-province-tr-turky', 'province', 'TURKY', 'TURKY', 'TR', CURRENT_TIMESTAMP),
  ('ref-province-tw-taiwan', 'province', 'TAIWAN', 'TAIWAN', 'TW', CURRENT_TIMESTAMP),
  ('ref-province-tw-to', 'province', 'TO', 'OTHER TAIWAN', 'TW', CURRENT_TIMESTAMP),
  ('ref-province-us-china-us', 'province', 'CHINA-US', 'CHINA-US', 'US', CURRENT_TIMESTAMP),
  ('ref-province-us1-china-us1', 'province', 'CHINA-US1', 'CHINA-US1', 'US1', CURRENT_TIMESTAMP),
  ('ref-province-us2-china-us2', 'province', 'CHINA-US2', 'CHINA-US2', 'US2', CURRENT_TIMESTAMP),
  ('ref-province-vas-vn-aus', 'province', 'VN-AUS', 'VN-AUS', 'VAS', CURRENT_TIMESTAMP),
  ('ref-province-vn-vietnam', 'province', 'VIETNAM', 'VIETNAM', 'VN', CURRENT_TIMESTAMP),
  ('ref-province-vus-v-in-usa', 'province', 'V-IN-USA', 'V-IN-USA', 'VUS', CURRENT_TIMESTAMP),
  ('ref-province-wait-wait', 'province', 'WAIT', 'WAIT', 'WAIT', CURRENT_TIMESTAMP),
  ('ref-province-wi-walk-in', 'province', 'WALK IN', 'WALK IN', 'WI', CURRENT_TIMESTAMP),
  ('ref-bustype-busagent', 'busType', 'BUSAGENT', 'BUS AGENT', '', CURRENT_TIMESTAMP),
  ('ref-bustype-busoa', 'busType', 'BUSOA', 'BUS OA', '', CURRENT_TIMESTAMP),
  ('ref-bustype-minibus', 'busType', 'MINIBUS', 'MINI BUS', '', CURRENT_TIMESTAMP),
  ('ref-bustype-taxi', 'busType', 'TAXI', 'TAXI / LIMOUSINE', '', CURRENT_TIMESTAMP),
  ('ref-bustype-vanagent', 'busType', 'VANAGENT', 'VAN AGENT', '', CURRENT_TIMESTAMP),
  ('ref-bustype-vanoa', 'busType', 'VANOA', 'VAN OA', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctait', 'charterCode', 'CTAIT', 'ชาร์เตอร์ AIT', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctcgb', 'charterCode', 'CTCGB', 'ชาร์เตอร์โกลบอล', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctcnlv', 'charterCode', 'CTCNLV', 'ชาร์เตอร์ นิวหลงไท่ CNLV', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctcxzyw', 'charterCode', 'CTCXZYW', 'ชาร์เตอร์ซูจิง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctds', 'charterCode', 'CTDS', 'ชาร์เตอร์ติ่งเซิ่ง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctdxt', 'charterCode', 'CTDXT', 'ชาร์เตอร์ต้าเซี่ยง DAXIANG', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctep', 'charterCode', 'CTEP', 'CHARTER ENPRO /ชาร์เตอร์เอ็นโปร', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctep1', 'charterCode', 'CTEP1', 'CHARTER ENPRO1 /ชาร์เตอร์เอ็นโปร1', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctfy', 'charterCode', 'CTFY', 'ชาเตอร์ ฟูหยวน', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctgb', 'charterCode', 'CTGB', 'ชาเตอร์โกลบอล', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cthx', 'charterCode', 'CTHX', 'ขาเตอร์หัวชิง HX', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctjcl', 'charterCode', 'CTJCL', 'ชาร์เตอร์ เจ ซี แอล JCL', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctjy', 'charterCode', 'CTJY', 'ชาร์เตอร์จิ่วหยุน JY', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctjyl', 'charterCode', 'CTJYL', 'ชาร์เตอร์จินหยุน JYL', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctllt', 'charterCode', 'CTLLT', 'ชาร์เตอร์LIAN TAI ( LLT )', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctllt1', 'charterCode', 'CTLLT1', 'ชาร์เตอร์เหลียนไท่ LLT1', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlltc', 'charterCode', 'CTLLTC', 'ชาเตอร์ LLTC', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctllth', 'charterCode', 'CTLLTH', 'ชาร์เตอร์ LLTH', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlltm', 'charterCode', 'CTLLTM', 'ชาร์เตอร์เหลียนไท่ LLTM', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctllts', 'charterCode', 'CTLLTS', 'ชาร์เตอร์เหลียนไท่ LLTS', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlltw', 'charterCode', 'CTLLTW', 'ชาร์เตอร์เหลียนไท่ LLTW', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlt', 'charterCode', 'CTLT', 'ชาร์เตอร์เหลียนไท่ (LT)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlt-2', 'charterCode', 'CTLT-2', 'ชาร์เตอร์เหลียนไท่ ( 2 )', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlta', 'charterCode', 'CTLTA', 'CHARTER LTA /ชาร์เตอร์ เหลียนไท่ LTA', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlth', 'charterCode', 'CTLTH', 'ชาเตอร์เหลียนไท่ (HONGTHAI)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctltj', 'charterCode', 'CTLTJ', 'ชาร์เตอร์เหลียนไท่ LTJ', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctltp', 'charterCode', 'CTLTP', 'ชาเตอร์ LTP(THAI HONG DA)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctltq', 'charterCode', 'CTLTQ', 'ชาร์เตอร์เหลียนไท  (LTQ)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlts', 'charterCode', 'CTLTS', 'ชาร์เตอร์LIAN TAI ( LTS )', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctltw', 'charterCode', 'CTLTW', 'ชาร์เตอร์เหลียนไท่ LTW', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctltx', 'charterCode', 'CTLTX', 'ชาร์เตอร์เหลียนไท่ LTX', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlv', 'charterCode', 'CTLV', 'ชาร์เตอร์หลงไท่', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlvm', 'charterCode', 'CTLVM', 'ชาร์เตอร์โคลเวอร์ LVM', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlx', 'charterCode', 'CTLX', 'ชาเตอร์หลงเถิง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlxwl', 'charterCode', 'CTLXWL', 'ชาร์เตอร์หลงเถิง LXWL', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctlxwy', 'charterCode', 'CTLXWY', 'ชาเตอร์หลงเถิง WY', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctmjtx', 'charterCode', 'CTMJTX', 'ชาร์เตอร์เหม่ยจิงเทียนเซี้ย', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctmtt', 'charterCode', 'CTMTT', 'ชาร์เตอร์เมทไทย', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctnjt', 'charterCode', 'CTNJT', 'ชาร์เตอร์นิวจินไท่', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctoct', 'charterCode', 'CTOCT', 'ชาเตอร์โอเวอร์ซีร์', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctpbrx', 'charterCode', 'CTPBRX', 'ชาร์เตอร์ พีบีอาร์เอ๊กซ์', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctpd', 'charterCode', 'CTPD', 'ชาเตอร์ พิมดี', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctqh', 'charterCode', 'CTQH', 'CHARTER QINGHER ชิงเหอ', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctsim', 'charterCode', 'CTSIM', 'ชาร์เตอร์สยามอินเตอร์ SIM', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctsxd', 'charterCode', 'CTSXD', 'ชาเตอร์ ซินต๋า ( SXD )', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttcq', 'charterCode', 'CTTCQ', 'ชาเตอร์ ไทชวนฉี (TCQ)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttfh', 'charterCode', 'CTTFH', 'ชาเตอร์ตงฟางฮอลิเดย์', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttht', 'charterCode', 'CTTHT', 'ชาร์เตอร์ไท่หงต๋า TAI HONG TA TRAVEL', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttjy', 'charterCode', 'CTTJY', 'ชาเตอร์ จิวหยุ่น TJY', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttkl', 'charterCode', 'CTTKL', 'ชาเตอร์ ทีเคแอล', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttkl-1', 'charterCode', 'CTTKL-1', 'ชาเตอร์ทีเคแอล1', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttng', 'charterCode', 'CTTNG', 'ชาร์เตอร์ไทยนิวเจน', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttnox', 'charterCode', 'CTTNOX', 'ชาร์เตอร์นิวโอเชียนTNOX', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctttx', 'charterCode', 'CTTTX', 'ชาเตอร์ไทยเทียนซุ่น', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttwx', 'charterCode', 'CTTWX', 'ชาร์เตอร์ไทว่านเซียง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttwy', 'charterCode', 'CTTWY', 'ชาร์เตอร์ไทหวังยู (TAI WANG YU)', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttxw', 'charterCode', 'CTTXW', 'ชาเตอร์ ไทซิงว่าง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-cttzt', 'charterCode', 'CTTZT', 'ชาเตอร์ ศุภโชคดี', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctvxd', 'charterCode', 'CTVXD', 'ชาเตอร์ ซินต๋า ( VXD )', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctwg', 'charterCode', 'CTWG', 'ชาร์เตอร์วั่นกั๋ว', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctxd', 'charterCode', 'CTXD', 'ชาเตอร์ ซินต๋า', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctykl', 'charterCode', 'CTYKL', 'ชาร์เตอร์ หยางกวง', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctykl-1', 'charterCode', 'CTYKL-1', 'ชาร์เตอร์ หยางกวง1', '', CURRENT_TIMESTAMP),
  ('ref-chartercode-ctym', 'charterCode', 'CTYM', 'ชาเตอร์ยูเหม่ย', '', CURRENT_TIMESTAMP)
ON CONFLICT ("type", "code", "nationCode") DO NOTHING;
