ALTER TABLE "LectureSession"
ADD COLUMN "lectureEndedAt" TIMESTAMP(3),
ADD COLUMN "lectureDurationSeconds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "cashierCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "salesAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "LectureHistory"
ADD COLUMN "lectureEndedAt" TIMESTAMP(3),
ADD COLUMN "lectureDurationSeconds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "totalDurationSeconds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "cashierCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "salesAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;
